### ISSUE TITLE
请停止使用盗用我们的网页

### ISSUE THREAD

**Issue by CubeWhy** [PlayMcBKuwu/playmcbkuwu.github.io#1]
百度统计代码暴露了

如下图

![-21ed64c2ed633121](https://github.com/PlayMcBKuwu/playmcbkuwu.github.io/assets/61075476/feb12515-96e2-4958-97b2-4421f5c03f27)

请你删除此存储库中盗用的代码，或加入lunarcn dev。

**Comment by muskf** [comment]
请立即删除index.html中的以下代码段
`<script src="https://hm.baidu.com/hm.js?ef9c555938fd3d70ea01c9648d1860d3"></script>`

**Comment by PlayMcBKuwu** [comment]
> https://hm.baidu.com/hm.js?ef9c555938fd3d70ea01c9648d1860d3



> 请立即删除index.html中的以下代码段 `<script src="https://hm.baidu.com/hm.js?ef9c555938fd3d70ea01c9648d1860d3"></script>`

删了，HTML 前面还有一个“网站非本人设计”，如果还有问题的话我会自己完全重新设计一个 HTML。

**Comment by CubeWhy** [comment]
> > 百度统计代码暴露了
> > 如下图
> > ![-21ed64c2ed633121](https://user-images.githubusercontent.com/61075476/245798516-feb12515-96e2-4958-97b2-4421f5c03f27.png)
> > 请你删除此存储库中盗用的代码，或加入lunarcn dev。
> 
> ### **如果发现百度统计代码中依旧有问题超过两周以上，我会立即删除此库以及 CN 库。**
> _（小声：我也想进 LunarCN Dev 啊，不会 Java 啊，扒了个 LunarCN.TOP 后还忘删百度统计代码版权问题肯定少不了啊）_

LunarCN Dev不全是写java的，如果你会html, js, php, go, py, java, kotlin中的其中一个，而且会熟练使用git，你就可以申请加入。

**Comment by muskf** [comment]
这个网页的源代码并非lunarcn原创,而是[https://github.com/Call-me-phoenix/css-effect-collection](url)这个库中选用的，我们只是要求你删除百度统计的代码，现在你已经删除了，可以关闭此议题

**Comment by PlayMcBKuwu** [comment]
> 这个网页的源代码并非lunarcn原创,而是[https://github.com/Call-me-phoenix/css-effect-collection](url)这个库中选用的，我们只是要求你删除百度统计的代码，现在你已经删除了，可以关闭此议题

好的，明白了

**Comment by CubeWhy** [comment]
> > > > 百度统计代码暴露了
> > > > 如下图
> > > > ![-21ed64c2ed633121](https://user-images.githubusercontent.com/61075476/245798516-feb12515-96e2-4958-97b2-4421f5c03f27.png)
> > > > 请你删除此存储库中盗用的代码，或加入lunarcn dev。
> > > 
> > > 
> > > ### **如果发现百度统计代码中依旧有问题超过两周以上，我会立即删除此库以及 CN 库。**
> > > _（小声：我也想进 LunarCN Dev 啊，不会 Java 啊，扒了个 LunarCN.TOP 后还忘删百度统计代码版权问题肯定少不了啊）_
> > 
> > 
> > LunarCN Dev不全是写java的，如果你会html, js, php, go, py, java, kotlin中的其中一个，而且会熟练使用git，你就可以申请加入。
> 
> GIT 会熟练用，HTML 会一点点，但是不多，CSS 还不会写

如果确认要加入的话请加我qq 1076124626，然后发送你写过的代码，如果我觉得符合要求，你以后就可以来开发了
